# 1. Warm-up: Rebuild the basics
**Goal:** Make array creation and inspection feel automatic.

Create each of the following arrays and print its shape, ndim, and dtype:

* A 1D array of integers from 10 to 19
* A 2D array of shape (4, 3) filled with 1.5
* A 3D array of zeros with shape (2, 2, 3)
* Convert the (4, 3) float array to integers using .astype(int).

* Write down (in a markdown cell) when you would prefer float vs int in real analyst work (e.g., prices vs counts).

In [177]:
import numpy as np

arr_1d = np.arange(10, 20)
print(f"1D_Array: \n{arr_1d}\n")

arr_2d = np.ones((4, 3)) * 1.5
print(f"2D_Array: \n{arr_2d}\n")

arr_3d = np.ones((2, 2, 3)) * 0
print(f"3D_Array: \n{arr_3d}\n")

1D_Array: 
[10 11 12 13 14 15 16 17 18 19]

2D_Array: 
[[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]

3D_Array: 
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]



I would use float for prices and int for whole numbers. Integer operations are usually faster than float operations, so if something could be saved as an Integer, I would probably convert it to that datatype. But generally, prices probably in float and counts in integers. 

# 2. Sales table drill: Indexing and slicing

Scenario: You have quarterly sales numbers for 4 regions (rows) over 5 quarters (columns).

```py
import numpy as np

sales = np.array([
    [120, 135, 110, 145, 130],  # Region A
    [ 90,  85,  95, 100, 110],  # Region B
    [200, 215, 190, 225, 245],  # Region C
    [155, 140, 135, 160, 170]   # Region D
])
regions = np.array(["A", "B", "C", "D"])
quarters = np.array(["Q1", "Q2", "Q3", "Q4", "Q5"])
```
Do the following:
1. Select all quarters for Region B as a 1D array.
2. Select Q2 to Q4 (inclusive) for all regions as a 2D subarray.
3. Select Q5 sales for Regions A and D only (use slicing or fancy indexing).
4. Compute the shape of each result and add a brief comment: “Is this 1D or 2D, and why?”

In [178]:
import numpy as np

sales = np.array([
    [120, 135, 110, 145, 130],  # Region A
    [ 90,  85,  95, 100, 110],  # Region B
    [200, 215, 190, 225, 245],  # Region C
    [155, 140, 135, 160, 170]   # Region D
])
regions = np.array(["A", "B", "C", "D"])
quarters = np.array(["Q1", "Q2", "Q3", "Q4", "Q5"])

In [179]:
# 1. Select all quarters for Region B as a 1D array.
region_b = sales[1]
print(f"Region B: \n{region_b}\n")

Region B: 
[ 90  85  95 100 110]



In [180]:
# 2. Select Q2 to Q4 (inclusive) for all regions as a 2D subarray.
q2_to_q4 = sales[:, 1:4] 
print(f"Q2 to Q4 for all regions: \n{q2_to_q4}\n")

Q2 to Q4 for all regions: 
[[135 110 145]
 [ 85  95 100]
 [215 190 225]
 [140 135 160]]



In [181]:
# 3. Select Q5 sales for Regions A and D only (use slicing or fancy indexing).
# slicing
region_a_d_q5_slice = sales[::3, -1:]
print(f"Region A & B Q5 (Slicing): \n{region_a_d_q5_slice}\n")

# fancy indexing
region_a_d_q5_fancy_index = sales[[0, -1], [-1, 4]]
print(f"Region A & B Q5 (Fancy indexing): \n{region_a_d_q5_fancy_index}\n")

Region A & B Q5 (Slicing): 
[[130]
 [170]]

Region A & B Q5 (Fancy indexing): 
[130 170]



In [182]:
# 4. Compute the shape of each result and add a brief comment: “Is this 1D or 2D, and why?”
print(f"Q1 shape: \n{region_b.shape}\n")

print(f"Q2 shape: \n{q2_to_q4.shape}\n")

print(f"Q3 shape(slice): \n{region_a_d_q5_slice.shape}\n")

print(f"Q3 shape(fancy index): \n{region_a_d_q5_fancy_index.shape}\n")

# Q1 results in a 1D array because there is only a row axis
# Q2 results in a 2D array because it was sliced using both axes, so it preserves its 2D shape
# Q3 using the slicing method results in a 2D array as well because both axes were used
# Q3 using the fancy indexing method results in a 1D array 

Q1 shape: 
(5,)

Q2 shape: 
(4, 3)

Q3 shape(slice): 
(2, 1)

Q3 shape(fancy index): 
(2,)



# 3. Boolean masks: Work with targets
1. Compute the ROI for each person: roi = revenue / spend.
2. Create a boolean mask for customers with roi >= 2.0.
3. Use the mask to:
    * List their names
    * List their spend and revenue
4. Create a second mask for customers with spend >= 200.
5. Combine the two masks to find customers who have roi >= 2.0 AND spend >= 200.
6. In a markdown cell, answer: “What business insight do you get from this filtered group?”


In [183]:
names = np.array(["Ana", "Ben", "Chen", "Dana", "Eli", "Fatima", "George", "Hui"])
spend = np.array([200, 150, 300, 120, 180, 220, 160, 310])      # marketing spend
revenue = np.array([400, 180, 500, 100, 220, 260, 150, 600])   # revenue

In [184]:
# 1. ROI
roi = (revenue / spend).round(2);
print(f"ROI: \n{roi}\n")

# 2. boolean mask for customers roi > 2.0
roi_gte_2 = roi >= 2

# 3. names, spend & revenue of people with ROI > 2
print(f"People with ROI >= 2.0: \n{names[roi_gte_2]}\n")
print(f"Spend of people ROI >= 2.0: \n{spend[roi_gte_2]}\n")
print(f"Revenue of people ROI >= 2.0: \n{revenue[roi_gte_2]}\n")

# 4. boolean mask for people with spend >= 200
spend_gte_200 = spend >= 200

# 5. Combine both masks, spend >= 200 AND roi >= 2.0
print(f"People who have ROI >= 2.0 & Spend >= 200: \n{names[roi_gte_2 & spend_gte_200]}\n")



ROI: 
[2.   1.2  1.67 0.83 1.22 1.18 0.94 1.94]

People with ROI >= 2.0: 
['Ana']

Spend of people ROI >= 2.0: 
[200]

Revenue of people ROI >= 2.0: 
[400]

People who have ROI >= 2.0 & Spend >= 200: 
['Ana']



6. This filtered group is the most valuable customer segment. This group should be prioritized for customer retention and may also serve as a profile for lookalike targeting. 

# 4. Gradebook: Aggregations and broadcasting
1. Compute each student’s average score (per row).
2. Compute each subject’s average score (per column).
3. Create scores_centered by subtracting the subject mean from each column (broadcasting).
4. For scores_centered, compute per-student averages again.
5. Compare which student looks best by raw average vs centered average.
6. In a markdown cell, explain briefly why centered scores might give a fairer comparison.

In [185]:
students = np.array(["S1", "S2", "S3", "S4", "S5"])
subjects = np.array(["Math", "Stats", "Python"])

scores = np.array([
    [75, 80, 85],
    [60, 65, 70],
    [90, 88, 92],
    [82, 79, 84],
    [70, 72, 78]
])

In [186]:
# 1. Each students avg score
avg_student_score = scores.mean(axis=1).round(2)
print(f"Average student scores: \n{avg_student_score}\n")

# 2. Each subjects avg score
avg_subject_score = scores.mean(axis=0).round(2)
print(f"Average subject scores: \n{avg_subject_score}\n")

# 3. 
scores_centered = scores - avg_subject_score
print(f"Scores Centered: \n{scores_centered}\n")

# 4. For scores_centered, compute per-student averages again.
avg_student_scores_centered = scores_centered.mean(axis=1).round(2)
print(f"Average student scores centered: \n{avg_student_scores_centered}\n")

Average student scores: 
[80.   65.   90.   81.67 73.33]

Average subject scores: 
[75.4 76.8 81.8]

Scores Centered: 
[[ -0.4   3.2   3.2]
 [-15.4 -11.8 -11.8]
 [ 14.6  11.2  10.2]
 [  6.6   2.2   2.2]
 [ -5.4  -4.8  -3.8]]

Average student scores centered: 
[  2.   -13.    12.     3.67  -4.67]



5. The best student seems to be Student 3 in both average score and average centered score.
6. It can more easily show students who perform better than the average and students who excel. So for students who didn't excel but still performed better than average, they are still easily visible.

# 5. Reshape and flatten: From daily to weekly
Scenario: You have 30 days of daily website visits, and you want to summarize them by week.
1. Reshape daily_visits into a (6, 5) array representing 6 weeks × 5 days.
2. Compute total visits per week.
3. Compute average visits per day of the week (e.g., all “day 1 of week” together, all “day 2 of week” together, etc.).
4. Flatten the reshaped array back to 1D and confirm it matches the original daily_visits.

Hint: Pay attention to how reshaping groups the data; mention any assumptions you’re making about which days belong to which week.

In [187]:
daily_visits = np.array([
    120, 130, 125, 140, 150,
    160, 170, 155, 145, 135,
    128, 132, 138, 142, 148,
    152, 158, 162, 168, 172,
    180, 190, 185, 175, 165,
    155, 145, 135, 125, 115
])

In [188]:
# 1. 
reshaped_daily_visits = daily_visits.reshape(6, 5)
print(f"Reshaped Daily Visits (6 weeks x 5 days): \n{reshaped_daily_visits}\n")

# 2. 
print(f"Total Visits per week: \n{reshaped_daily_visits.sum(axis=1)}\n")

# 3. 
print(f"Average visits per day of the week: \n{reshaped_daily_visits.mean(axis=0).round(2)}\n")

# 4. 
flatten_daily_visits = reshaped_daily_visits.flatten()
print(flatten_daily_visits == daily_visits)

Reshaped Daily Visits (6 weeks x 5 days): 
[[120 130 125 140 150]
 [160 170 155 145 135]
 [128 132 138 142 148]
 [152 158 162 168 172]
 [180 190 185 175 165]
 [155 145 135 125 115]]

Total Visits per week: 
[665 765 688 812 895 675]

Average visits per day of the week: 
[149.17 154.17 150.   149.17 147.5 ]

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]


# 6. Mini-project: Simple scoring model
1. Choose a weight vector w = [w_views, w_time, w_purchases] (for example [0.1, 0.5, 1.0]).
2. Compute a score for each customer using scores = X @ w.
3. Rank customers by score (highest first).
4. Change the weights to emphasize past_purchases more than other features, and recompute.
5. In a markdown cell, answer:
    * Which customer is top-ranked before vs after changing weights?
    * In what real-world situation might you prefer each weighting?

In [189]:
# Each row: [page_views, time_on_site (minutes), past_purchases]
X = np.array([
    [10,  3.5,  0],
    [25,  5.0,  1],
    [40,  2.0,  0],
    [15, 10.0,  3],
    [30,  4.0,  2]
])

customers = np.array(["C1", "C2", "C3", "C4", "C5"])

In [190]:
# More emphasis on new customers
weight = np.array([0.4, 1.0, 0.8])
customer_score = X @ weight
print(f"Customers scores: \n{customer_score}\n")

ranked_indices = np.argsort(customer_score)[::-1]
print(customers[ranked_indices])
print(customer_score[ranked_indices])

print("\n")


# New weights emphasis on past purchases
weight_new = np.array([0.1, 0.4, 2.0])
customer_score_new = X @ weight_new
print(f"Customers scores: \n{customer_score_new}\n")

ranked_indices_new = np.argsort(customer_score_new)[::-1]
print(customers[ranked_indices_new])
print(customer_score_new[ranked_indices_new])



Customers scores: 
[ 7.5 15.8 18.  18.4 17.6]

['C4' 'C3' 'C5' 'C2' 'C1']
[18.4 18.  17.6 15.8  7.5]


Customers scores: 
[ 2.4  6.5  4.8 11.5  8.6]

['C4' 'C5' 'C2' 'C3' 'C1']
[11.5  8.6  6.5  4.8  2.4]


- **First weighting** [0.2, 1.0, 0.8]: Useful for a **new customer campaign** where 
  time spent on site is the strongest signal. These are engaged browsers who 
  haven't purchased much yet and are worth targeting.

- **Second weighting** [0.1, 0.2, 2.0]: Useful for a **loyalty/retention campaign** 
  where past purchases is more important. Rewarding and retaining your best buyers.

# 7. Stretch ideas (optional)
If you’re comfortable with the above, try:

* Generate 1,000 random test scores with np.random.randn, scale them to have mean 70 and standard deviation 10, then:
    * Clip scores to the range [0, 100]
    * Compute min, max, mean, and standard deviation
* Simulate a small A/B test:
    * Two groups of 20 users each
    * Randomly generate conversions (0 or 1) for each group
    * Compute conversion rate per group using pure NumPy operations

In [195]:
np.random.seed(42)
scores = np.random.randn(1000) * 10 + 70

scores = np.clip(scores, 0, 100)

print(f"Min: {scores.min().round(2)}")
print(f"Max: {scores.max().round(2)}")
print(f"Mean: {scores.mean().round(2)}")   # should be ~70
print(f"Std: {scores.std().round(2)}")     # should be ~10


Min: 37.59
Max: 100.0
Mean: 70.18
Std: 9.76
